version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: db_v2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_blog_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_v2
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: php-blog
    container_name: app_v2
    restart: always
    ports:
      - "8000:80"
    depends_on:
      - db
    volumes:
      - .:/var/www/html
      
volumes:
  mysql-data:
